Updated everything except Rake
Rake is stuck at version 11 because of:

NoMethodError: undefined method `last_comment' for
#<Rake::Application:0x007fddcf8080b8>